import Head from 'next/head'
import Login from '../../components/login/Login'
import Logo from '../../components/logo/Logo'
import CenterItemPage from '../../layouts/CenterItemPage'
import UsuarioExternoWrapper from '../../sessionWrapper/UsuarioExternoWrapper'

const Index = () => {
    return <UsuarioExternoWrapper>

        <Head>
            <title>Comite</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <CenterItemPage>
            <Logo />
            <Login title="consultor senior" route="consultor-senior"/>
        </CenterItemPage>

    </UsuarioExternoWrapper>
}

export default Index
