import Head from 'next/head'
import Login from '../../components/login/Login'
import UsuarioExternoWrapper from '../../sessionWrapper/UsuarioExternoWrapper'

const Index = () => {
    return <UsuarioExternoWrapper>

        <Head>
            <title>Comite</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Comite</h1>
        <Login title="usuario externo" route="usuario-externo"/>
        <style jsx>{`

        `}</style>
    </UsuarioExternoWrapper>
}

export default Index
