import ValidateCode from '../../components/register/ValidateCode'
import UsuarioExternoWrapper from '../../sessionWrapper/UsuarioExternoWrapper'
import Head from 'next/head'
import CenterItemPage from '../../layouts/CenterItemPage'
import Logo from '../../components/logo/Logo'

const ValidarCodigo = () => {
    return <UsuarioExternoWrapper>

        <Head>
            <title>Comite</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <CenterItemPage>
            <Logo />
            <ValidateCode route="usuario-externo"/>
        </CenterItemPage>

    </UsuarioExternoWrapper>
}

export default ValidarCodigo
