import Head from 'next/head'
import Login from '../../components/login/Login'
import ComiteWrapper from '../../sessionWrapper/ComiteWrapper'

const Index = () => {
    return <ComiteWrapper>

        <Head>
            <title>Comite</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Comite</h1>
        <Login title="comite" route="comite"/>
        <style jsx>{`

        `}</style>
    </ComiteWrapper>
}

export default Index
