import ValidateCode from '../../components/register/ValidateCode'
import ComiteWrapper from '../../sessionWrapper/ComiteWrapper'
import Head from 'next/head'
import Logo from '../../components/logo/Logo'
import CenterItemPage from '../../layouts/CenterItemPage'

const ValidarCodigo = () => {
    return <ComiteWrapper>

        <Head>
            <title>Comite</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <CenterItemPage>
            <Logo />
            <ValidateCode route="comite"/>
        </CenterItemPage>

    </ComiteWrapper>
}

export default ValidarCodigo
