import Head from 'next/head'
const Index = () => {
    return <div className="container">

        <Head>
            <title>ConsulTIC</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>ConsulTIC</h1>

        <style jsx>{`

        `}</style>
    </div>
}

export default Index
