import Head from 'next/head'
import axios from 'axios'
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router'
import Amplify from "@aws-amplify/core";
import Auth from "@aws-amplify/auth";

import { amplifyConfigAdmin, authConfigAdmin } from '../cognito/consultorioPool'

Amplify.configure(amplifyConfigAdmin)
Auth.configure(authConfigAdmin)

import { signIn, signUp } from '../utils/authFunctions'

const Index = () => {

	const [SignUpData, setSignUpData] = useState({
		email: '',
		password: ''
	})
	const [SignInData, setSignInData] = useState({
		email: '',
		password: ''
	})
	const [numeros, setNumeros] = useState([])

	useEffect(() => {
		/* getData() */
	}, []);

	const readSignUpData = (e) => {
		setSignUpData(Object.assign({}, SignUpData, { [e.target.name]: e.target.value }))
	}

	const readSgnInData = (e) => {
		setSignInData(Object.assign({}, SignInData, { [e.target.name]: e.target.value }))
	}

	const getData = async () => {
		const response = await axios.get('/api/hello')
		setNumeros(response.data.data.Items)
	}

	const onClick = async () => {
		const number = String(Date.now())
		const response = await axios.post('/api/hello', { number })
		setNumeros(numList => [...numList, { id: { S: number } }])
		console.log(response)
	}

	const register = async (e) => {
		/* e.preventDefault() */
		e.preventDefault()
		const { user, err } = await signUp(SignUpData)
		console.log(user, err)
	}

	const router = useRouter()

	const login = async (e) => {
		console.log(SignInData)
		const err = await signIn(e, SignInData, router)
		console.log(err)
	}

	return <div className="container">

		<Head>
			<title>ConsulTIC</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<h1>ConsulTIC</h1>
		<div>

			<h2>Prueba de concepto de AWS Cognito</h2>
			<h3>Sign up</h3>
			<form onSubmit={register}>
				<input type="text" onChange={readSignUpData} placeholder="email" name="email" />
				<br />
				<input type="password" onChange={readSignUpData} placeholder="password" name="password" />
				<button>Sign up</button>
			</form>
			<h3>Sign in</h3>
			<form onSubmit={login}>
				<input type="text" onChange={readSgnInData} placeholder="email" name="email" />
				<br />
				<input type="password" onChange={readSgnInData} placeholder="password" name="password" />
				<button>Sign in</button>
			</form>
		</div>
		<div>
			<h2>Prueba de concepto de AWS DynamoDB</h2>
			<button onClick={onClick}>
				Save number random number in DB
			</button>
			<ul>
				{
					numeros.map(num => (
						<li key={num.id.S}>{num.id.S}</li>
					))
				}
			</ul>
		</div>

		<style jsx>{`

		.container {
			display: grid;
			min-height: 100vh;
			place-items: center;
			grid-row-gap: 2rem;
			padding: 2rem;
		}

		button {
			display: block;
			margin: auto;
		}

		input {
			width: 100%;
		}

		`}</style>
	</div>
}

export default Index
