import Head from 'next/head'
import Login from '../../components/login/Login'
import ConsultorioSeniorWrapper from '../../sessionWrapper/ConsultorioSeniorWrapper'

const Index = () => {
    return <ConsultorioSeniorWrapper>

        <Head>
            <title>Comite</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Comite</h1>
        <Login title="consultor senior" route="consultor-senior"/>
        <style jsx>{`

        `}</style>
    </ConsultorioSeniorWrapper>
}

export default Index
