import ValidateCode from '../../components/register/ValidateCode'
import ConsultorioSeniorWrapper from '../../sessionWrapper/ConsultorioSeniorWrapper'
import Head from 'next/head'
import CenterItemPage from '../../layouts/CenterItemPage'
import Logo from '../../components/logo/Logo'

const ValidarCodigo = () => {
    return <ConsultorioSeniorWrapper>

        <Head>
            <title>Comite</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <CenterItemPage>
            <Logo />
            <ValidateCode route="consultor-senior"/>
        </CenterItemPage>

    </ConsultorioSeniorWrapper>
}

export default ValidarCodigo
