import ConsultorioJuniorWrapper from '../../sessionWrapper/ConsultorioJuniorWrapper'
import Head from 'next/head'

const Index = () => {
    return <ConsultorioJuniorWrapper verify>

        <Head>
            <title>Admin</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1>pagina privada</h1>

        <style jsx>{`
            
        `}</style>
    </ConsultorioJuniorWrapper>
}

export default Index
