import Head from 'next/head'
import Login from '../../components/login/Login'
import ConsultorioJuniorWrapper from '../../sessionWrapper/ConsultorioJuniorWrapper'

const Index = () => {
    return <ConsultorioJuniorWrapper>

        <Head>
            <title>Comite</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Comite</h1>
        <Login title="consultor junior" route="consultor-junior"/>
        <style jsx>{`

        `}</style>
    </ConsultorioJuniorWrapper>
}

export default Index
