import Logo from '../../components/logo/Logo'
import ValidateCode from '../../components/register/ValidateCode'
import CenterItemPage from '../../layouts/CenterItemPage'
import ConsultorioJuniorWrapper from '../../sessionWrapper/ConsultorioJuniorWrapper'
import Head from 'next/head'

const ValidarCodigo = () => {
    return <ConsultorioJuniorWrapper>

        <Head>
            <title>Comite</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <CenterItemPage>
            <Logo />
            <ValidateCode route="consultor-junior"/>
        </CenterItemPage>

    </ConsultorioJuniorWrapper>
}

export default ValidarCodigo
