import Head from 'next/head'
import Login from '../../components/login/Login'
import AdminWrapper from '../../sessionWrapper/AdminWrapper'

const Index = () => {
    return <AdminWrapper>

        <Head>
            <title>Admin</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1>Admin</h1>
        <Login title="admin" route="admin"/>
        <style jsx>{`

        `}</style>
    </AdminWrapper>
}

export default Index
