import ValidateCode from '../../components/register/ValidateCode'
import CenterItemPage from '../../layouts/CenterItemPage'
import AdminWrapper from '../../sessionWrapper/AdminWrapper'
import Head from 'next/head'
import Logo from '../../components/logo/Logo'

const ValidarCodigo = () => {
    return <AdminWrapper>

        <Head>
            <title>Admin</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <CenterItemPage>
            <Logo />
            <ValidateCode route="admin"/>
        </CenterItemPage>

    </AdminWrapper>
}

export default ValidarCodigo
